apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquito-api
spec:
  # GOAL: Lock down specifications to limit potential charges
  replicas: 1  # Run only one instance to prevent autoscaling
  selector:
    matchLabels:
      app: mosquito-api
  template:
    metadata:
      labels:
        app: mosquito-api
    spec:
      containers:
        - name: mosquito-api
          image: us-central1-docker.pkg.dev/elytech-mosquito/mosquito-repo/mosquito-api-ca:latest
          ports:
            - containerPort: 8000

          env:
            - name: ENVIRONMENT
              value: "production"

          resources:

            # Minimum resources guaranteed to this container can be pretty small.
            # The Kubernetes scheduler uses this to place the container on a node.

            requests:
              cpu: "50m"        # 0.05 CPU cores (1/20 of a core)
              memory: "64Mi"    # 64 MiB RAM

            # Maximum allowed resource usage
            # If the container exceeds these, the container may be throttled or killed
            limits:
              cpu: "100m"       # 0.1 CPU cores max
              memory: "128Mi"   # 128 MiB RAM max

